name: snowpalm
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.13
  - numpy
  - netcdf4
  - gdal
  - pip
  - scipy
  - pyproj
  - python-dateutil
  - pillow
  - ipykernel
  - requests
  - tqdm
  - libgdal-netcdf
